import type { Session, Organization, User } from './types';

// ─── Mock user ────────────────────────────────────────────────────────────────

export const mockUser: User = {
  id: 'user-kai',
  firstName: 'Kai',
  lastName: 'Johnson',
  email: 'kai.johnson@student.vsb.bc.ca',
  school: 'Lord Byng Secondary',
  grade: 11,
  graduationYear: 2026,
  phone: '6045550194',
  phoneVerified: true,
  plan: 'free',
  nhsGoalHours: 75,
  nhsGoalStartDate: '2024-09-03',
  nhsGoalDeadline: '2025-05-30',
};

// ─── Organizations ────────────────────────────────────────────────────────────

export const mockOrganizations: Organization[] = [
  {
    id: 'org-1',
    slug: 'greater-vancouver-food-bank',
    name: 'Greater Vancouver Food Bank',
    category: 'Community',
    address: '1150 Raymur Ave, Vancouver, BC V6A 3T2',
    website: 'https://www.foodbank.bc.ca',
    ein: '12-3456789',
    registrationStatus: 'institutional',
    description: 'Supporting communities by collecting and distributing food to those in need.',
  },
  {
    id: 'org-2',
    slug: 'bc-spca-vancouver',
    name: 'BC SPCA — Vancouver Branch',
    category: 'Animal welfare',
    address: '1205 E 7th Ave, Vancouver, BC V5T 1R1',
    website: 'https://spca.bc.ca',
    ein: '98-7654321',
    registrationStatus: 'registered',
    description: 'Protecting and caring for animals across British Columbia.',
  },
  {
    id: 'org-3',
    slug: 'burnaby-public-library',
    name: 'Burnaby Public Library',
    category: 'Education',
    address: '7311 Kingsway, Burnaby, BC V3N 3C7',
    website: 'https://www.bpl.bc.ca',
    registrationStatus: 'institutional',
    description: 'Free public library services for the Burnaby community.',
  },
  {
    id: 'org-4',
    slug: 'terry-fox-run',
    name: 'Terry Fox Run — Lower Mainland',
    category: 'Health',
    address: 'Various locations across Metro Vancouver',
    website: 'https://terryfox.org',
    registrationStatus: 'registered',
    description: 'Annual fundraising run in honour of Terry Fox to support cancer research.',
  },
  {
    id: 'org-5',
    slug: 'north-van-seniors-centre',
    name: 'North Vancouver Seniors Centre',
    category: 'Social services',
    address: '3600 Brooksbank Ave, North Vancouver, BC V7J 2B6',
    website: 'https://nvrc.ca',
    registrationStatus: 'registered',
    description: 'Programs and services supporting seniors in North Vancouver.',
  },
  {
    id: 'org-6',
    slug: 'covenant-house-vancouver',
    name: 'Covenant House Vancouver',
    category: 'Social services',
    address: '575 Drake St, Vancouver, BC V6B 4K8',
    website: 'https://covenanthousebc.org',
    ein: '55-4432211',
    registrationStatus: 'registered',
    description: 'Supporting homeless youth in Vancouver with shelter and programs.',
  },
  {
    id: 'org-7',
    slug: 'pacific-salmon-foundation',
    name: 'Pacific Salmon Foundation',
    category: 'Environment',
    address: '1682 W 7th Ave, Vancouver, BC V6J 4S6',
    website: 'https://psf.ca',
    registrationStatus: 'registered',
    description: 'Protecting and restoring wild Pacific salmon and their ecosystems.',
  },
  {
    id: 'org-8',
    slug: 'ywca-metro-vancouver',
    name: 'YWCA Metro Vancouver',
    category: 'Community',
    address: '535 Hornby St, Vancouver, BC V6C 2E8',
    website: 'https://ywcavan.org',
    registrationStatus: 'institutional',
    description: 'Empowering women and girls through programs in housing, childcare, and employment.',
  },
];

// ─── Sessions ─────────────────────────────────────────────────────────────────
// 28 sessions across the 2024–25 school year. Distributed to make the
// 8-week activity chart look realistic, with a mix of verified/pending/disputed.

export const mockSessions: Session[] = [
  // ── September 2024 ──────────────────────────────────────────────────────
  {
    id: 's-01',
    org: 'Greater Vancouver Food Bank',
    orgSlug: 'greater-vancouver-food-bank',
    date: '2024-09-07',
    hours: 4,
    activity: 'Sorting and packing incoming food donations for distribution',
    supervisor: 'Sarah Kim',
    supervisorPhone: '6045550201',
    status: 'verified',
    tier: 'institution',
    verifiedAt: '2024-09-07T18:23:00',
  },
  {
    id: 's-02',
    org: 'North Vancouver Seniors Centre',
    orgSlug: 'north-van-seniors-centre',
    date: '2024-09-14',
    hours: 3,
    activity: 'Companion visits and bingo coordination with residents',
    supervisor: 'Linda Boychuk',
    supervisorPhone: '6045550302',
    status: 'verified',
    tier: 'supervisor',
    verifiedAt: '2024-09-14T15:41:00',
  },
  {
    id: 's-03',
    org: 'Burnaby Public Library',
    orgSlug: 'burnaby-public-library',
    date: '2024-09-21',
    hours: 4,
    activity: 'Fall reading program assistant — helped kids select books and set up displays',
    supervisor: 'Priya Sharma',
    supervisorPhone: '6045550403',
    status: 'verified',
    tier: 'institution',
    verifiedAt: '2024-09-21T17:05:00',
  },
  // ── October 2024 ────────────────────────────────────────────────────────
  {
    id: 's-04',
    org: 'BC SPCA — Vancouver Branch',
    orgSlug: 'bc-spca-vancouver',
    date: '2024-10-05',
    hours: 3.5,
    activity: 'Dog walking, kennel cleaning, and socialising with cats in adoption wing',
    supervisor: 'James Lee',
    supervisorPhone: '6045550504',
    status: 'verified',
    tier: 'supervisor',
    verifiedAt: '2024-10-05T14:11:00',
  },
  {
    id: 's-05',
    org: 'Greater Vancouver Food Bank',
    orgSlug: 'greater-vancouver-food-bank',
    date: '2024-10-12',
    hours: 4,
    activity: 'Warehouse organisation and loading delivery vehicles',
    supervisor: 'Sarah Kim',
    supervisorPhone: '6045550201',
    status: 'verified',
    tier: 'institution',
    verifiedAt: '2024-10-12T18:50:00',
  },
  {
    id: 's-06',
    org: 'Pacific Salmon Foundation',
    orgSlug: 'pacific-salmon-foundation',
    date: '2024-10-19',
    hours: 5,
    activity: 'Streamside habitat restoration — removed invasive plants near Mosquito Creek',
    supervisor: 'Anika Johal',
    supervisorPhone: '6045550605',
    status: 'verified',
    tier: 'supervisor',
    verifiedAt: '2024-10-19T16:22:00',
  },
  {
    id: 's-07',
    org: 'Covenant House Vancouver',
    orgSlug: 'covenant-house-vancouver',
    date: '2024-10-26',
    hours: 4,
    activity: 'Meal service and common area setup for evening drop-in program',
    supervisor: 'Marcus Chen',
    supervisorPhone: '6045550706',
    status: 'disputed',
    tier: null,
    notes: 'Supervisor reported incorrect hours — follow up needed.',
  },
  // ── November 2024 ────────────────────────────────────────────────────────
  {
    id: 's-08',
    org: 'Burnaby Public Library',
    orgSlug: 'burnaby-public-library',
    date: '2024-11-02',
    hours: 4,
    activity: 'Homework help club — assisted grade 5–7 students with math and science',
    supervisor: 'Priya Sharma',
    supervisorPhone: '6045550403',
    status: 'verified',
    tier: 'institution',
    verifiedAt: '2024-11-02T17:33:00',
  },
  {
    id: 's-09',
    org: 'YWCA Metro Vancouver',
    orgSlug: 'ywca-metro-vancouver',
    date: '2024-11-09',
    hours: 3,
    activity: 'Front desk reception support and childcare room assistant',
    supervisor: 'Fatima Al-Hassan',
    supervisorPhone: '6045550807',
    status: 'verified',
    tier: 'institution',
    verifiedAt: '2024-11-09T16:10:00',
  },
  {
    id: 's-10',
    org: 'North Vancouver Seniors Centre',
    orgSlug: 'north-van-seniors-centre',
    date: '2024-11-16',
    hours: 3,
    activity: 'Chair yoga assistant and afternoon tea social coordination',
    supervisor: 'Linda Boychuk',
    supervisorPhone: '6045550302',
    status: 'verified',
    tier: 'supervisor',
    verifiedAt: '2024-11-16T15:58:00',
  },
  {
    id: 's-11',
    org: 'Greater Vancouver Food Bank',
    orgSlug: 'greater-vancouver-food-bank',
    date: '2024-11-23',
    hours: 4,
    activity: 'Holiday hamper packing event — sorted and assembled 200+ boxes',
    supervisor: 'Sarah Kim',
    supervisorPhone: '6045550201',
    status: 'verified',
    tier: 'institution',
    verifiedAt: '2024-11-23T19:15:00',
  },
  // ── December 2024 ────────────────────────────────────────────────────────
  {
    id: 's-12',
    org: 'BC SPCA — Vancouver Branch',
    orgSlug: 'bc-spca-vancouver',
    date: '2024-12-07',
    hours: 3.5,
    activity: 'Holiday adoption event — groomed animals and assisted potential adopters',
    supervisor: 'James Lee',
    supervisorPhone: '6045550504',
    status: 'verified',
    tier: 'supervisor',
    verifiedAt: '2024-12-07T16:44:00',
  },
  {
    id: 's-13',
    org: 'Covenant House Vancouver',
    orgSlug: 'covenant-house-vancouver',
    date: '2024-12-14',
    hours: 4,
    activity: 'Winter gift wrapping station and holiday dinner service',
    supervisor: 'Marcus Chen',
    supervisorPhone: '6045550706',
    status: 'verified',
    tier: 'supervisor',
    verifiedAt: '2024-12-14T20:03:00',
  },
  // ── January 2025 ─────────────────────────────────────────────────────────
  {
    id: 's-14',
    org: 'Burnaby Public Library',
    orgSlug: 'burnaby-public-library',
    date: '2025-01-11',
    hours: 4,
    activity: 'Winter reading challenge — set up displays and registered participants',
    supervisor: 'Priya Sharma',
    supervisorPhone: '6045550403',
    status: 'verified',
    tier: 'institution',
    verifiedAt: '2025-01-11T17:20:00',
  },
  {
    id: 's-15',
    org: 'YWCA Metro Vancouver',
    orgSlug: 'ywca-metro-vancouver',
    date: '2025-01-18',
    hours: 3,
    activity: 'Drop-in program support and activity facilitation',
    supervisor: 'Fatima Al-Hassan',
    supervisorPhone: '6045550807',
    status: 'verified',
    tier: 'institution',
    verifiedAt: '2025-01-18T15:55:00',
  },
  {
    id: 's-16',
    org: 'Pacific Salmon Foundation',
    orgSlug: 'pacific-salmon-foundation',
    date: '2025-01-25',
    hours: 4,
    activity: 'Salmon egg planting in Capilano River tributary with restoration team',
    supervisor: 'Anika Johal',
    supervisorPhone: '6045550605',
    status: 'verified',
    tier: 'supervisor',
    verifiedAt: '2025-01-25T14:40:00',
  },
  // ── February 2025 ────────────────────────────────────────────────────────
  {
    id: 's-17',
    org: 'Greater Vancouver Food Bank',
    orgSlug: 'greater-vancouver-food-bank',
    date: '2025-02-01',
    hours: 4,
    activity: 'Inventory audit and restocking of non-perishable items',
    supervisor: 'Sarah Kim',
    supervisorPhone: '6045550201',
    status: 'verified',
    tier: 'institution',
    verifiedAt: '2025-02-01T18:30:00',
  },
  {
    id: 's-18',
    org: 'North Vancouver Seniors Centre',
    orgSlug: 'north-van-seniors-centre',
    date: '2025-02-15',
    hours: 3,
    activity: "Valentine’s social — set up decorations and ran card-making activity",
    supervisor: 'Linda Boychuk',
    supervisorPhone: '6045550302',
    status: 'verified',
    tier: 'supervisor',
    verifiedAt: '2025-02-15T16:00:00',
  },
  // ── March 2025 ───────────────────────────────────────────────────────────
  {
    id: 's-19',
    org: 'Burnaby Public Library',
    orgSlug: 'burnaby-public-library',
    date: '2025-03-01',
    hours: 4,
    activity: 'Spring reading program — story time sessions and craft setup',
    supervisor: 'Priya Sharma',
    supervisorPhone: '6045550403',
    status: 'verified',
    tier: 'institution',
    verifiedAt: '2025-03-01T17:45:00',
  },
  {
    id: 's-20',
    org: 'YWCA Metro Vancouver',
    orgSlug: 'ywca-metro-vancouver',
    date: '2025-03-15',
    hours: 3,
    activity: "International Women's Day event — setup and registration desk",
    supervisor: 'Fatima Al-Hassan',
    supervisorPhone: '6045550807',
    status: 'verified',
    tier: 'institution',
    verifiedAt: '2025-03-15T18:20:00',
  },
  // ── April 2025 ───────────────────────────────────────────────────────────
  {
    id: 's-21',
    org: 'Pacific Salmon Foundation',
    orgSlug: 'pacific-salmon-foundation',
    date: '2025-04-05',
    hours: 5,
    activity: 'Earth Day preparation — trail clearing and signage installation',
    supervisor: 'Anika Johal',
    supervisorPhone: '6045550605',
    status: 'verified',
    tier: 'supervisor',
    verifiedAt: '2025-04-05T16:35:00',
  },
  {
    id: 's-22',
    org: 'Greater Vancouver Food Bank',
    orgSlug: 'greater-vancouver-food-bank',
    date: '2025-04-19',
    hours: 4,
    activity: 'Spring fundraising drive — sorted donated goods and updated inventory',
    supervisor: 'Sarah Kim',
    supervisorPhone: '6045550201',
    status: 'verified',
    tier: 'institution',
    verifiedAt: '2025-04-19T17:10:00',
  },
  // ── May 2025 ─────────────────────────────────────────────────────────────
  {
    id: 's-23',
    org: 'Terry Fox Run — Lower Mainland',
    orgSlug: 'terry-fox-run',
    date: '2025-05-03',
    hours: 6,
    activity: 'Setup and water station volunteer — managed hydration station for 400+ runners',
    supervisor: 'Marcus Chen',
    supervisorPhone: '6045550706',
    status: 'verified',
    tier: 'institution',
    verifiedAt: '2025-05-03T16:45:00',
  },
  {
    id: 's-24',
    org: 'North Vancouver Seniors Centre',
    orgSlug: 'north-van-seniors-centre',
    date: '2025-05-10',
    hours: 3,
    activity: "Mother's Day crafts session — assisted residents with card making",
    supervisor: 'Linda Boychuk',
    supervisorPhone: '6045550302',
    status: 'verified',
    tier: 'supervisor',
    verifiedAt: '2025-05-10T15:30:00',
  },
  // ── June 2025 ────────────────────────────────────────────────────────────
  {
    id: 's-25',
    org: 'Burnaby Public Library',
    orgSlug: 'burnaby-public-library',
    date: '2025-06-03',
    hours: 4,
    activity: 'Summer reading program assistant — helped kids find books and fill out logs',
    supervisor: 'Priya Sharma',
    supervisorPhone: '6045550403',
    status: 'pending',
    tier: null,
  },
  {
    id: 's-26',
    org: 'BC SPCA — Vancouver Branch',
    orgSlug: 'bc-spca-vancouver',
    date: '2025-06-08',
    hours: 3.5,
    activity: 'Dog walking and kennel cleaning — morning shift',
    supervisor: 'James Lee',
    supervisorPhone: '6045550504',
    status: 'verified',
    tier: 'supervisor',
    verifiedAt: '2025-06-08T14:11:00',
  },
  {
    id: 's-27',
    org: 'North Vancouver Seniors Centre',
    orgSlug: 'north-van-seniors-centre',
    date: '2025-06-12',
    hours: 3,
    activity: "End-of-year party setup and cleanup for the seniors' social club",
    supervisor: 'Linda Boychuk',
    supervisorPhone: '6045550302',
    status: 'pending',
    tier: null,
  },
  {
    id: 's-28',
    org: 'Greater Vancouver Food Bank',
    orgSlug: 'greater-vancouver-food-bank',
    date: '2025-06-14',
    hours: 4,
    activity: 'Sorting and packing donations — helped process a large weekend drop-off',
    supervisor: 'Sarah Kim',
    supervisorPhone: '6045550201',
    status: 'verified',
    tier: 'institution',
    verifiedAt: '2025-06-14T18:23:00',
  },
];

// ─── Derived helpers ──────────────────────────────────────────────────────────

export function getTotalHours(sessions: Session[]): number {
  return sessions
    .filter(s => s.status === 'verified')
    .reduce((sum, s) => sum + s.hours, 0);
}

export function getVerifiedRate(sessions: Session[]): number {
  if (sessions.length === 0) return 0;
  const verified = sessions.filter(s => s.status === 'verified').length;
  return Math.round((verified / sessions.length) * 100);
}

export function getActiveOrgsCount(sessions: Session[]): number {
  return new Set(sessions.map(s => s.orgSlug)).size;
}
